#!/bin/tcsh
#PBS -N HASPECT_SW
#PBS -m abe 
#PBS -M Derek.Glazier@glasgow.ac.uk
#PBS -l walltime=100:00:00
#PBS -V
#Make a directory to work in
#mkdir -p /home/dglazier/$JOBNAME
#cd /home/dglazier/$JOBNAME
mkdir -p /scratch/dglazier/$JOBNAME
cd /scratch/dglazier/$JOBNAME

echo ' analysing bin ' $JOBNAME
echo $HOST

#set env variables
setenv INPUT "Farm"$JOBNAME".root"
setenv LOG "Farm"$JOBNAME".log"

#IMPORTANT!!!!!!!!!!
#copy data and analysis files
scp dglazier@npc72:$FILEDIR/$INPUT .
cp $RUNMAC .
cp $HSANA/THSRooFit.C .
cp $HSANA/THSBins.C .
cp $HSANA/THSRooFit.h .
cp $HSANA/THSBins.h .
cp $HSANA/THSWeights.C .
cp $HSANA/THSWeights.h .
cp $HSANA/THSsPlot.C .
cp $HSANA/THSsPlot.h .
cp $HSANA/THSEventsPDF.C .
cp $HSANA/THSEventsPDF.h .

ls -lh 
#run job in root batch mode
#root -b -q '$RUNMAC(TString(gSystem->Getenv("JOBNAME")))' 
root -b -q '$RUNMAC(TString(gSystem->Getenv("JOBNAME")))'  >& $LOG

#copy output files to destination
scp Results* dglazier@npc72:$FILEDIR/.
scp Weights* dglazier@npc72:$FILEDIR/.
scp $LOG dglazier@npc72:$FILEDIR/.

ls -lh 

#tidy up
cd ../
rm -r $JOBNAME

echo 'all done and tidied up'


